#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : whitespace
Version  : 1.0.0b8
Release  : 3
URL      : https://files.pythonhosted.org/packages/0e/db/4addd92b7f4b24673447073c5bd7c5fb288eed27f3e66d03609f5a498f56/whitespace-1.0.0b8.tar.gz
Source0  : https://files.pythonhosted.org/packages/0e/db/4addd92b7f4b24673447073c5bd7c5fb288eed27f3e66d03609f5a498f56/whitespace-1.0.0b8.tar.gz
Summary  : A Whitespace interpreter.
Group    : Development/Tools
License  : MIT
Requires: whitespace-bin = %{version}-%{release}
Requires: whitespace-python = %{version}-%{release}
Requires: whitespace-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
Whitespace
==========
.. image:: https://img.shields.io/pypi/v/whitespace.svg
:target: https://pypi.org/project/whitespace/

%package bin
Summary: bin components for the whitespace package.
Group: Binaries

%description bin
bin components for the whitespace package.


%package python
Summary: python components for the whitespace package.
Group: Default
Requires: whitespace-python3 = %{version}-%{release}

%description python
python components for the whitespace package.


%package python3
Summary: python3 components for the whitespace package.
Group: Default
Requires: python3-core

%description python3
python3 components for the whitespace package.


%prep
%setup -q -n whitespace-1.0.0b8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571163900
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/whitespace

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
